version: '3.9'

volumes:
  keycloak_db_data:
    driver: local

services:
  keycloak_db:
    container_name: keycloak_db
    restart: always
    image: postgres:13.3
    ports:
      - 15432:5432
    volumes:
      - type: volume
        source: keycloak_db_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak_app:
    container_name: keycloak_app
    restart: always
    image: quay.io/keycloak/keycloak:latest
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/npd-realm-export.json -Dkeycloak.migration.strategy=IGNORE_EXISTING"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: m
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 18080:8080
    volumes:
      - type: bind
        source: ./keycloak-files/npd-realm-export.json
        target: /opt/jboss/keycloak/imports/npd-realm-export.json
    depends_on:
      - keycloak_db
